def funcao_para_retornar_o_numero_inicial_da_soma_da_funcao_de_somar_numeros_que_estao_em_uma_lista_de_numeros():
    return 0


def funcao_para_retornar_a_lista_de_numeros_que_vou_passar_para_a_funcao_de_somar_numeros_que_estao_em_uma_lista_de_numeros():
    return [1, 12, 23, 21, 23, 1, 2]


def funcao_pra_somar_numeros_que_estao_em_uma_lista_de_numeros(lista_de_numeros_que_foi_passada_para_a_funcao):
    soma_total_dos_numeros_da_lista_de_numeros_que_foi_passada_para_a_funcao = funcao_para_retornar_o_numero_inicial_da_soma_da_funcao_de_somar_numeros_que_estao_em_uma_lista_de_numeros()
    for numero_atual_da_lista_de_numeros_que_foi_passada_para_a_funcao in lista_de_numeros_que_foi_passada_para_a_funcao:
        soma_total_dos_numeros_da_lista_de_numeros_que_foi_passada_para_a_funcao += numero_atual_da_lista_de_numeros_que_foi_passada_para_a_funcao
    return soma_total_dos_numeros_da_lista_de_numeros_que_foi_passada_para_a_funcao


lista_que_eu_vou_passar_para_a_funcao_de_somar_numeros_que_estao_em_uma_lista_de_numeros = funcao_para_retornar_a_lista_de_numeros_que_vou_passar_para_a_funcao_de_somar_numeros_que_estao_em_uma_lista_de_numeros()

print(funcao_pra_somar_numeros_que_estao_em_uma_lista_de_numeros(
    lista_que_eu_vou_passar_para_a_funcao_de_somar_numeros_que_estao_em_uma_lista_de_numeros))
